import {
  BadgeCheck,
  CalendarClock,
  Clock,
  Coins,
  CreditCard,
  GraduationCap,
  Globe2,
  HandCoins,
  Heart,
  Languages,
  LineChart,
  MapPin,
  Mail,
  MessageCircle,
  PiggyBank,
  Rocket,
  Search,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  UserPlus,
  Users,
  Video,
  Wallet,
} from "lucide-react";

/** String-keyed icon registry so page content data can stay serialisable. */
export const ICONS = {
  shield: ShieldCheck,
  wallet: Wallet,
  calendar: CalendarClock,
  globe: Globe2,
  sparkles: Sparkles,
  graduation: GraduationCap,
  message: MessageCircle,
  video: Video,
  card: CreditCard,
  clock: Clock,
  heart: Heart,
  users: Users,
  star: Star,
  badge: BadgeCheck,
  search: Search,
  mail: Mail,
  coins: Coins,
  handCoins: HandCoins,
  target: Target,
  languages: Languages,
  mapPin: MapPin,
  piggy: PiggyBank,
  trending: TrendingUp,
  userPlus: UserPlus,
  rocket: Rocket,
  chart: LineChart,
} as const;

export type IconKey = keyof typeof ICONS;
